{% set version = "5.9" %}

package:
  name: ncurses
  version: {{ version }}

source:
  fn: ncurses-{{ version }}.tar.gz
  url: http://ftp.gnu.org/pub/gnu/ncurses/ncurses-{{ version }}.tar.gz
  md5: 8cb9c412e5f2d96bc6f459aa8c6282a1
  patches:
    # http://lists.gnu.org/archive/html/bug-ncurses/2011-04/txtkWQqiQvcZe.txt
    - fix.patch
    # http://lists.gnu.org/archive/html/bug-ncurses/2015-01/msg00016.html
    - ncurses-5.9-gcc-5.patch

build:
  skip: true  # [win]
  number: 2
  detect_binary_files_with_prefix: true

test:
  files:
    - run_test.sh         # [osx]
    - run_test.py         # [osx]
  commands:
    - test -f ${PREFIX}/lib/libncursesw.a
    - test -f ${PREFIX}/lib/libtinfow.a
    - test -f ${PREFIX}/lib/libformw.a
    - test -f ${PREFIX}/lib/libmenuw.a
    - test -f ${PREFIX}/lib/libpanelw.a

    - bash run_test.sh    # [osx]
    - python run_test.py  # [osx]

about:
  home: http://www.gnu.org/software/ncurses/
  license: Free software (MIT-like License)
  summary: Library for text-based user interfaces

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
