# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cBBulDUSF4IvI59O9g1YmrYzAdOgnMFQh4rpEnz6guOioj+pqjw2tisuW9oVnbxNTDqYJJkCK3fyCsS6oONAVS2W4qvWCeLJp8kRjfvEr6S5hLOmMi8nJs+6fXf5UvlBtWGofJ7NExQIxbh4Zgd+cfrirMrYLqt5DHlc041UxPBd8E9LO3CwfN8fXJbgKh1xy0mJz+Ru6d79neP/3s1taVreRCcv+F30ZYCWclIfgo+Bn1JfRnLLY4qMVFZVE10hvJWEvT4M1Bj1icu2bBXyL6ay6qhmlLuIS6fFJk7jpLj/qWi+rl9q/XKJt4ILmyV4apeKrJFQ7N7uwLg/NxgjeEHOkjx9+5yanbGCKLuJj+J8+HweFl2thdrda9v0STH3AsISBdu1llaxcMjnYbJqHVt/xrbv3cJyFo6ucljmEsHH4PNH4r6OJt4sCV1njkAB6YXnIel5Bmk+qUSsLtM4c3vN+6x/lBSGSEmK8vualnRVHiOKef5JYKLfKsJPNutLtdBt18DFJa5ebl36snhROAbZHpN3ydD6HRADYL7AXOiOZ9aeVylMXviNVprkl/g/Ii0RQuaOd0yNG7LFMZpNvKu8my4MdRr053glqMkgLH8WrRjY+H7rcUltGd/hR1AECYkPGvF6sMk2JSjwwc7pLbXSepphlHy92Q4BOf3lpWQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
