version: 2

jobs:
<<<<<<< HEAD
  build_linux_c_compilergcccxx_compilergxx:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_c_compilergcccxx_compilergxx"
=======
  build_linux_:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_"
>>>>>>> MNT: Re-rendered with conda-smithy 3.1.5 and pinning 2018.05.22
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
<<<<<<< HEAD
  build_linux_c_compilertoolchain_ccxx_compilertoolchain_cxx:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_c_compilertoolchain_ccxx_compilertoolchain_cxx"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
=======
>>>>>>> MNT: Re-rendered with conda-smithy 3.1.5 and pinning 2018.05.22

workflows:
  version: 2
  build_and_test:
    jobs:
<<<<<<< HEAD
      - build_linux_c_compilergcccxx_compilergxx
      - build_linux_c_compilertoolchain_ccxx_compilertoolchain_cxx
=======
      - build_linux_
>>>>>>> MNT: Re-rendered with conda-smithy 3.1.5 and pinning 2018.05.22
